import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>India's Best Online / Offline Personal Tution Classes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="main bg-[linear-gradient(45deg,#f90588,#5a2776)] w-screen h-[100vh]"></div>
      </div>
    </>
  )
}
