import Head from 'next/head'
// #f90588,#5a2776


export default function Home() {
  return (
    <>
      <Head>
        <title>India's Best Online / Offline Personal Tution Classes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <div>
        <div className="main">
          <div className="landing w-screen h-screen flex-col flex items-center justify-center bg-[url(https://img.freepik.com/free-vector/hand-drawn-minimal-background_23-2149017896.jpg?w=996&t=st=1671991157~exp=1671991757~hmac=db41c0b2cfdcc5048148d23ddbe525f69db785f9a3c6d7574d683644defda41c)] bg-cover">
            <h1 className='text-9xl font-semibold text-[#5a2776]'>Need A Tution ?</h1>
            <h2 className='my-5  text-xl w-[60vw] text-center'>With Personal Assistance - Doubt Solving - ExtraTime - No Leaves - And More Benifts At Low Cost - Everything At One Place For Every Class And Subject</h2>
          </div>
          <div className="whyus my-10 w-screen h-screen flex-col flex items-center justify-center">
            <h2 className='text-6xl'>Send Your Child And See The Improvement</h2>
            <p className='w-[60vw] my-5 text-center'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo provident maiores nisi iste dolore debitis eum dolores, laborum vitae magni ea et tenetur ab, commodi ipsam, repudiandae unde! Reprehenderit corporis quam velit quod aut.</p>
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuw73B2JTDysTXxwpvJFa6QbCNowYZehjGpA&usqp=CAU"
              className='w-96 my-10 p-10 rounded-xl shadow-[20px_20px_0_#f90588]'   alt="" />
          </div>
          <div className="difference my-10 w-screen h-screen flex-col flex items-center justify-center">
            <h1 className='text-6xl'>Why We Made A Difference ?</h1>
            <p className='w-[60vw] my-5 text-center'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo provident maiores nisi iste dolore debitis eum dolores, laborum vitae magni ea et tenetur ab, commodi ipsam, repudiandae unde! Reprehenderit corporis quam velit quod aut.</p>
            <div className="cards container bg-[#f90588] h-[300px] my-10 rounded-xl flex justify-center">
              <div className="card bg-white w-1/4 h-[400px] rounded-xl shadow-2xl mt-20 mx-10 flex flex-col items-center justify-center">
                <h1 className='text-3xl uppercase font-bold text-[#5a2776] text-center my-10'>All Subjects</h1>
                <img src="https://static.vecteezy.com/system/resources/thumbnails/002/175/498/small_2x/school-subjects-icons-set-free-vector.jpg" className='w-[80%] rounded-xl' alt="" />
              </div>
              <div className="card bg-white w-1/4 h-[400px] rounded-xl shadow-2xl mt-20 mx-10 flex flex-col items-center justify-center">
                <h1 className='text-3xl uppercase font-bold text-[#5a2776] text-center my-10'>PYQs DPPs Tests</h1>
                <img src="https://icons.veryicon.com/png/o/miscellaneous/ecological-desktop-icon-library/test-11.png" className='w-[80%] rounded-xl' alt="" />
              </div>
              <div className="card bg-white w-1/4 h-[400px] rounded-xl shadow-2xl mt-20 mx-10 flex flex-col items-center justify-center">
                <h1 className='text-3xl uppercase font-bold text-[#5a2776] text-center my-10'>Extra Classes</h1>
                <img src="https://cdni.iconscout.com/illustration/premium/thumb/student-studying-in-classroom-4036137-3345618.png" className='w-[80%] rounded-xl' alt="" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
